name: ocr_visitor
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+4
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_mlkit_text_recognition: ^0.10.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  meta: ^1.9.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  shared_preferences: ^2.2.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
